name: normalize-assets

on:
  pull_request:
    paths:
      - "EmbeddedModLoader/assets/**"

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: normalize with ffmpeg
        run: |
          for f in $(find EmbeddedModLoader/assets -type f); do
            ext="${f##*.}"
            base="${f%.*}"
            case "$ext" in
              png|jpg|jpeg|gif|webp)
                ffmpeg -y -i "$f" -vf "scale=-1:250:force_original_aspect_ratio=decrease" "${base}.tmp.$ext"
                mv "${base}.tmp.$ext" "$f"
                ;;
              wav|mp3|ogg|flac)
                ffmpeg -y -i "$f" -ar 44100 "${base}.tmp.$ext"
                mv "${base}.tmp.$ext" "$f"
                ;;
            esac
          done

      - name: check for diffs
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "assets not normalized. run the pipeline locally or grab the artifact."
            git status --short
            exit 1
          fi
