name: normalize-assets

on:
  workflow_dispatch:

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: normalize with ffmpeg
        run: |
          find EmbeddedModLoader/assets -type f | while IFS= read -r f; do
            ext="${f##*.}"
            base="${f%.*}"
            case "$ext" in
              png|jpg|jpeg|gif|webp)
                ffmpeg -y -i "$f" -vf "scale=-1:250:force_original_aspect_ratio=decrease" "${base}.tmp.$ext"
                mv "${base}.tmp.$ext" "$f"
                ;;
              wav|mp3|ogg|flac)
                ffmpeg -y -i "$f" -ar 44100 "${base}.tmp.$ext"
                mv "${base}.tmp.$ext" "$f"
                ;;
            esac
          done

      - name: commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add EmbeddedModLoader/assets
            git commit -m "normalize assets (images <=250px height, audio = 44.1kHz)"
            git push
          fi
